name: Break docker containers

on:
  workflow_dispatch:
    user:
      - benchungiscool

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Overwrite dockerfiles
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning
            rm docker/*
            echo "FROM python:bookworm\n"" >> docker/client_Dockerfile
            echo "WORKDIR /app" >> docker/client_Dockerfile
            echo "COPY requirements.txt /app/requirements.txt" >> docker/client_Dockerfile
            echo "COPY src /app/" >> docker/client_Dockerfile
            echo "RUN pip install --no-cache-dir -r requirements.txt" >> docker/client_Dockerfile
            echo "FROM python:bookworm\n"" >> docker/server_Dockerfile
            echo "WORKDIR /app" >> docker/server_Dockerfile
            echo "COPY requirements.txt /app/requirements.txt" >> docker/server_Dockerfile
            echo "COPY src /app/" >> docker/server_Dockerfile
            echo "RUN pip install --no-cache-dir -r requirements.txt" >> docker/server_Dockerfile

      - name: Build docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning
            docker-compose build
            docker push benchungbenchung/k8s_test:server001
            docker push benchungbenchung/k8s_test:client001
