name: Break docker containers

on:
  workflow_dispatch:
    user:
      - benchungiscool

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Overwrite dockerfiles
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning/docker
            mv client_Dockerfile wrong_client_Dockerfile
            mv server_Dockerfile wrong_server_Dockerfile
            mv correct_client_Dockerfile client_Dockerfile
            mv correct_server_Dockerfile server_Dockerfile

      - name: Build docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning
            docker-compose build
            docker push benchungbenchung/k8s_test:server001
            docker push benchungbenchung/k8s_test:client001
